name: Publish

on:
  release:
    types: [created]

jobs:

  publish-github-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@gardenabot"
      - run: npm ci
      - run: npm run prepare
      - run: echo "registry=https://npm.pkg.github.com/@gardenabot" >> .npmrc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GIT_PCK_TOKEN}}
